enableGlobalCache: true

enableInlineBuilds: true

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - arm
    - ia32
    - x64
    - x86
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.3.1.cjs
