name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  CI: true

jobs:
  # Checks files with ESLint and Prettier
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: 0xTheProDev/setup-js@v1.1
        with:
          cache: yarn
          version-file: .nvmrc

      - name: Lint all files
        shell: bash
        run: yarn lint

  # Runs unit tests
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: 0xTheProDev/setup-js@v1.1
        with:
          cache: yarn
          version-file: .nvmrc

      - name: Run all tests
        shell: bash
        run: yarn test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: 0xTheProDev/setup-js@v1.1
        with:
          cache: yarn
          version-file: .nvmrc

      - name: Build
        shell: bash
        run: yarn build
