name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  CI: true

jobs:
  # Checks files with ESLint and Prettier
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: 0xTheProDev/setup-js@v1
        with:
          cache: yarn
          version-file: .nvmrc

      - name: Lint all files
        run: yarn lint

  # Runs unit tests
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: 0xTheProDev/setup-js@v1
        with:
          cache: yarn
          version-file: .nvmrc

      - name: Run all tests
        run: yarn test

  # Ensures all projects can build
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: 0xTheProDev/setup-js@v1
        with:
          cache: yarn
          version-file: .nvmrc

      - name: Build
        run: yarn build
