name: CI

on: [pull_request]

env:
  CI: true

jobs:
  # Checks files with ESLint and Prettier
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .nvmrc
      - name: Install dependencies
        run: yarn
      - name: Lint all files
        run: yarn lint

  # Runs unit tests
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .nvmrc
      - name: Install dependencies
        run: yarn
      - name: Run all tests
        run: yarn test

  # Ensures all projects can build
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .nvmrc
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
